security:
   basic:
     enabled: false

management:
      security:
          enabled: false

logging:
   level:
     io:
       pivotal: DEBUG


greeting:
    displayFortune: true

quoteService: http://quote-service-dev.cfapps.io/quote
